/**
 * Bundles product guide markdown for Alter chat (user/admin/getting-started).
 * Run via yarn pretest / yarn sync-guide-docs. Output is committed for Docker.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../..");
const documentationDir = path.join(repoRoot, "documentation");
const outFile = path.join(__dirname, "../src/data/guideDocs.generated.js");

export const GUIDE_BUNDLE_PREFIXES = [
  "INDEX.md",
  "user-guide/",
  "admin-guide/",
  "getting-started/",
];

const isBundledKey = (rel) =>
  GUIDE_BUNDLE_PREFIXES.some(
    (p) => rel === p || rel.startsWith(p) || (p.endsWith(".md") && rel === p)
  );

function walkMarkdown(dir, baseDir, acc) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdown(abs, baseDir, acc);
      continue;
    }
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) continue;
    const rel = path.relative(baseDir, abs).split(path.sep).join("/");
    if (!isBundledKey(rel)) continue;
    acc[rel] = fs.readFileSync(abs, "utf8");
  }
}

function main() {
  if (!fs.existsSync(documentationDir)) {
    process.stderr.write(
      `syncGuideDocs: documentation/ not found at ${documentationDir}\n`
    );
    process.exit(1);
  }

  const docs = {};
  walkMarkdown(documentationDir, documentationDir, docs);

  const keys = Object.keys(docs).sort();
  if (!docs["INDEX.md"]) {
    throw new Error("documentation/INDEX.md is required");
  }
  if (!docs["user-guide/docs.md"]) {
    throw new Error("documentation/user-guide/docs.md is required");
  }

  const banner =
    "/** Generated by scripts/syncGuideDocs.js — do not edit. */\n";
  const body = `export const GUIDE_DOCS = ${JSON.stringify(docs, null, 2)};\n`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, banner + body, "utf8");
  process.stdout.write(
    `syncGuideDocs: wrote ${keys.length} files to ${path.relative(
      repoRoot,
      outFile
    )}\n`
  );
}

main();
