/**
 * Bundles documentation/*.md (and INDEX-linked docs/*.md) into a TS manifest.
 * Run from frontend via prestart / prebuild / pretest.
 */
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "../..");
const documentationDir = path.join(repoRoot, "documentation");
const outFile = path.join(
  __dirname,
  "../src/pages/guide/guideDocs.generated.ts"
);

const EXTRA_DOCS = [
  "docs/alt-board-form-manual.md",
  "docs/reservation-feature-design.md",
];

function walkMarkdown(dir, baseDir, acc) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdown(abs, baseDir, acc);
      continue;
    }
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) continue;
    const rel = path.relative(baseDir, abs).split(path.sep).join("/");
    acc[rel] = fs.readFileSync(abs, "utf8");
  }
}

function main() {
  if (!fs.existsSync(documentationDir)) {
    throw new Error(`documentation/ not found at ${documentationDir}`);
  }

  const docs = {};
  walkMarkdown(documentationDir, documentationDir, docs);

  for (const rel of EXTRA_DOCS) {
    const abs = path.join(repoRoot, rel);
    if (!fs.existsSync(abs)) {
      throw new Error(`extra guide file missing: ${rel}`);
    }
    docs[rel] = fs.readFileSync(abs, "utf8");
  }

  const keys = Object.keys(docs).sort();
  if (!docs["INDEX.md"]) {
    throw new Error("documentation/INDEX.md is required");
  }

  const banner =
    "/* eslint-disable */\n" +
    "/** Generated by scripts/syncGuideDocs.js — do not edit. */\n";
  const body = `export const GUIDE_DOCS: Record<string, string> = ${JSON.stringify(
    docs,
    null,
    2
  )};\n`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, banner + body, "utf8");
  process.stdout.write(
    `syncGuideDocs: wrote ${keys.length} files to ${path.relative(
      repoRoot,
      outFile
    )}\n`
  );
}

main();
