name: test-login-pipeline

on:
  push:
    branches: [test-login]

jobs:
  test-login:
    name: test-login
    runs-on: ubuntu-latest

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # GitHub 컨테이너 레지스트리에 로그인

      # 1. unknown user
      # - name: Login to ghcr
      #   uses: docker/login-action@v2.0.0
      #   with:
      #     registry: ghcr.io/bmrdevteam
      #     username: "unknown"
      #     password: "wrong password"

      # 2. wrong password
      - name: Login to ghcr
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io/bmrdevteam
          username: ${{ github.actor }}
          password: "wrong password"

      # 3. correct password
      - name: Login to ghcr
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io/bmrdevteam
          username: ${{ github.actor }}
          password: ${{ secrets[format('TEST_VAL_{0}', github.actor)] }}

      # 슬랙 알림
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Chatbot - test login
          fields: repo,commit,message,author,action,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
